# Dockerfile.api
FROM python:3.9

# Crear el directorio de trabajo
WORKDIR /app

# Copiar el archivo de la API a /app
COPY main.py /app

# Instalar FastAPI y Uvicorn
RUN pip install fastapi uvicorn

# Exponer el puerto 8000
EXPOSE 8000

# Comando para ejecutar la API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
