version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"      # Expone la API en el puerto 8000
    volumes:
      - .:/app           # Mapea la carpeta actual al contenedor para reflejar cambios
    depends_on:
      - ffmpeg

  ffmpeg:
    build:
      context: .
      dockerfile: Dockerfile.ffmpeg
    volumes:
      - .:/app           # Mapea la carpeta actual al contenedor para acceso compartido
