# Dockerfile.api
FROM python:3.9

WORKDIR /app

COPY main.py /app
COPY first_seminar.py /app  # Asegúrate de copiar también este archivo para que esté disponible

RUN pip install fastapi uvicorn numpy opencv-python-headless scipy pywavelets pillow

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
